import type { Product, ProductCategory } from "@/types";
import { getProductImages } from "@/lib/images";

export const categories: ProductCategory[] = [
  "iPhone",
  "MacBook",
  "iPad",
  "Apple Watch",
  "AirPods",
  "Apple TV",
  "HomePod",
  "Accessories",
  "Cases",
  "Chargers",
  "Power Banks",
  "Screen Protectors",
  "Adapters",
  "Cables",
  "Speakers",
  "Smart Accessories",
  "Gaming",
  "PlayStation",
  "Xbox",
  "Nintendo",
  "Controllers",
  "Gaming Headsets"
];

export const products: Product[] = [
  {
    id: "iphone-16-pro-max",
    slug: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    category: "iPhone",
    series: "iPhone 16 Series",
    price: 1299,
    compareAtPrice: 1399,
    rating: 4.9,
    reviewCount: 128,
    images: getProductImages("iphone-16-pro-max"),
    colors: ["Natural Titanium", "Black Titanium", "Desert Titanium"],
    storage: ["256GB", "512GB", "1TB"],
    condition: ["New", "Used", "Refurbished"],
    batteryHealth: "95%+ for used inventory",
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "Same-day pickup or 1-3 business days delivery",
    badge: "Best Seller",
    description:
      "A flagship iPhone experience with a large display, pro camera system, powerful performance, and premium titanium finish.",
    specs: {
      Display: "6.9-inch Super Retina class OLED",
      Chip: "Latest-generation A-series performance",
      Camera: "Pro camera system with advanced zoom",
      Security: "Face ID",
      Charging: "USB-C"
    },
    bestSeller: true,
    newArrival: true,
    deal: true
  },
  {
    id: "iphone-16",
    slug: "iphone-16",
    name: "iPhone 16",
    category: "iPhone",
    series: "iPhone 16 Series",
    price: 899,
    rating: 4.8,
    reviewCount: 94,
    images: getProductImages("iphone-16"),
    colors: ["Ultramarine", "Pink", "Black", "White"],
    storage: ["128GB", "256GB", "512GB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "1-3 business days delivery",
    badge: "New",
    description: "A modern everyday iPhone with excellent performance, camera quality, and battery life.",
    specs: {
      Display: "6.1-inch OLED",
      Chip: "A-series chip",
      Camera: "Dual-camera system",
      Connectivity: "5G",
      Charging: "USB-C"
    },
    newArrival: true
  },
  {
    id: "iphone-15-pro",
    slug: "iphone-15-pro",
    name: "iPhone 15 Pro",
    category: "iPhone",
    series: "iPhone 15 Series",
    price: 999,
    compareAtPrice: 1099,
    rating: 4.8,
    reviewCount: 211,
    images: getProductImages("iphone-15-pro"),
    colors: ["Natural Titanium", "Blue Titanium", "White Titanium"],
    storage: ["128GB", "256GB", "512GB"],
    condition: ["New", "Used", "Refurbished"],
    batteryHealth: "90%+ for used inventory",
    availability: "Low Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "1-2 business days delivery",
    description: "Pro-level iPhone performance in a refined titanium design with excellent camera features.",
    specs: {
      Display: "6.1-inch OLED",
      Chip: "A17 Pro class",
      Camera: "Pro camera system",
      Material: "Titanium",
      Charging: "USB-C"
    },
    deal: true
  },
  {
    id: "macbook-air-13-m3",
    slug: "macbook-air-13-m3",
    name: "MacBook Air 13-inch",
    category: "MacBook",
    series: "MacBook Air",
    price: 1099,
    rating: 4.9,
    reviewCount: 77,
    images: getProductImages("macbook-air-13-m3"),
    colors: ["Midnight", "Starlight", "Space Gray", "Silver"],
    storage: ["256GB", "512GB", "1TB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "1-3 business days delivery",
    badge: "Student Pick",
    description: "Thin, silent, and powerful enough for work, study, design tasks, and daily productivity.",
    specs: {
      Display: "13.6-inch Liquid Retina class",
      Processor: "Apple silicon",
      Memory: "8GB or 16GB unified memory",
      Battery: "All-day battery life",
      Ports: "MagSafe, Thunderbolt, headphone jack"
    },
    bestSeller: true
  },
  {
    id: "macbook-pro-14",
    slug: "macbook-pro-14",
    name: "MacBook Pro 14-inch",
    category: "MacBook",
    series: "MacBook Pro",
    price: 1999,
    compareAtPrice: 2199,
    rating: 4.9,
    reviewCount: 63,
    images: getProductImages("macbook-pro-14"),
    colors: ["Space Black", "Silver"],
    storage: ["512GB", "1TB", "2TB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "2-4 business days delivery",
    description: "A high-performance MacBook for creators, engineers, and business professionals.",
    specs: {
      Display: "14.2-inch XDR class display",
      Processor: "Pro-grade Apple silicon",
      Memory: "18GB+ unified memory options",
      Battery: "Long-lasting professional workflow battery",
      Ports: "HDMI, SDXC, MagSafe, Thunderbolt"
    },
    deal: true
  },
  {
    id: "ipad-pro-13",
    slug: "ipad-pro-13",
    name: "iPad Pro 13-inch",
    category: "iPad",
    series: "iPad Pro",
    price: 1299,
    rating: 4.8,
    reviewCount: 54,
    images: getProductImages("ipad-pro-13"),
    colors: ["Space Black", "Silver"],
    storage: ["256GB", "512GB", "1TB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "1-3 business days delivery",
    badge: "Creator Favorite",
    description: "A premium tablet for creative work, note-taking, entertainment, and portable productivity.",
    specs: {
      Display: "13-inch Ultra Retina class display",
      Chip: "Pro-grade Apple silicon",
      Accessories: "Keyboard and Pencil compatible",
      Camera: "Advanced front and rear cameras",
      Charging: "USB-C"
    },
    newArrival: true
  },
  {
    id: "ipad-air-11",
    slug: "ipad-air-11",
    name: "iPad Air 11-inch",
    category: "iPad",
    series: "iPad Air",
    price: 699,
    rating: 4.7,
    reviewCount: 88,
    images: getProductImages("ipad-air-11"),
    colors: ["Blue", "Purple", "Starlight", "Space Gray"],
    storage: ["128GB", "256GB", "512GB"],
    condition: ["New", "Used", "Refurbished"],
    batteryHealth: "92%+ for used inventory",
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "1-3 business days delivery",
    description: "A light, capable iPad for study, business, creativity, and entertainment.",
    specs: {
      Display: "11-inch Liquid Retina class",
      Chip: "Apple silicon",
      Camera: "Landscape front camera",
      Accessories: "Keyboard and Pencil compatible",
      Charging: "USB-C"
    }
  },
  {
    id: "apple-watch-series-10",
    slug: "apple-watch-series-10",
    name: "Apple Watch Series",
    category: "Apple Watch",
    series: "Apple Watch Series",
    price: 429,
    rating: 4.8,
    reviewCount: 109,
    images: getProductImages("apple-watch-series-10"),
    colors: ["Jet Black", "Rose Gold", "Silver"],
    storage: ["GPS", "GPS + Cellular"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "Same-day pickup available",
    badge: "Health Pick",
    description: "A refined smartwatch for fitness, communication, health insights, and everyday convenience.",
    specs: {
      Display: "Always-On Retina class display",
      Health: "Heart, sleep, and activity tracking",
      Water: "Swim-ready design",
      Connectivity: "GPS and cellular options",
      Bands: "Multiple band sizes available"
    },
    bestSeller: true
  },
  {
    id: "airpods-pro",
    slug: "airpods-pro",
    name: "AirPods Pro",
    category: "AirPods",
    series: "AirPods",
    price: 249,
    compareAtPrice: 279,
    rating: 4.9,
    reviewCount: 156,
    images: getProductImages("airpods-pro"),
    colors: ["White"],
    storage: ["USB-C Case"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "Same-day pickup available",
    badge: "Deal",
    description: "Premium wireless earbuds with immersive listening, noise control, and compact charging.",
    specs: {
      Audio: "Adaptive noise control",
      Case: "USB-C charging case",
      Fit: "Multiple ear tip sizes",
      Pairing: "Instant setup with compatible devices",
      Controls: "Touch controls"
    },
    bestSeller: true,
    deal: true
  },
  {
    id: "magnetic-charger",
    slug: "magnetic-charger",
    name: "Magnetic Fast Charger",
    category: "Chargers",
    series: "Apple accessories",
    price: 39,
    rating: 4.7,
    reviewCount: 43,
    images: getProductImages("magnetic-charger"),
    colors: ["White", "Black"],
    storage: ["1m Cable", "2m Cable"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "6-month TroyX warranty",
    deliveryEstimate: "Same-day pickup available",
    description: "A compact magnetic charger for compatible devices, ideal for desk and bedside charging.",
    specs: {
      Type: "Magnetic wireless charger",
      Cable: "USB-C",
      Compatibility: "Compatible Apple devices",
      Use: "Desk, travel, bedside",
      Warranty: "6 months"
    },
    newArrival: true
  },
  {
    id: "iphone-clear-case",
    slug: "iphone-clear-case",
    name: "Protective Clear Case",
    category: "Cases",
    series: "Apple accessories",
    price: 29,
    rating: 4.6,
    reviewCount: 67,
    images: getProductImages("iphone-clear-case"),
    colors: ["Clear", "Smoke"],
    storage: ["iPhone 15", "iPhone 16", "iPhone 16 Pro"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "30-day accessory warranty",
    deliveryEstimate: "Same-day pickup available",
    description: "A slim protective case that keeps the device design visible while adding everyday protection.",
    specs: {
      Material: "Shock-resistant polymer",
      Finish: "Clear protective shell",
      Fit: "Model-specific fit",
      Grip: "Raised edges and tactile buttons",
      Warranty: "30 days"
    }
  },
  {
    id: "usb-c-power-bank",
    slug: "usb-c-power-bank",
    name: "USB-C Power Bank",
    category: "Power Banks",
    series: "Smart Accessories",
    price: 79,
    rating: 4.7,
    reviewCount: 32,
    images: getProductImages("usb-c-power-bank"),
    colors: ["Graphite", "Silver"],
    storage: ["10,000mAh", "20,000mAh"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "6-month TroyX warranty",
    deliveryEstimate: "1-2 business days delivery",
    description: "A portable USB-C battery pack for travel days, work commutes, and backup power.",
    specs: {
      Capacity: "10,000mAh or 20,000mAh",
      Ports: "USB-C and USB-A",
      Charging: "Fast-charge capable",
      Indicators: "LED battery status",
      Warranty: "6 months"
    }
  },

  // Gaming - PlayStation
  {
    id: "ps5",
    slug: "ps5",
    name: "PlayStation 5",
    category: "Gaming",
    series: "PlayStation 5",
    price: 599,
    rating: 4.9,
    reviewCount: 245,
    images: getProductImages("ps5"),
    colors: ["White", "Black"],
    storage: ["Disc Edition", "Digital Edition"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month manufacturer warranty",
    deliveryEstimate: "1-2 business days delivery",
    badge: "Popular",
    description: "Next-generation gaming console with ultra-high speed SSD, custom GPU, and exclusive games library.",
    specs: {
      Processor: "Custom AMD Ryzen Zen 2",
      GPU: "Custom RDNA 2 GPU",
      Memory: "16GB GDDR6",
      Storage: "825GB SSD",
      Resolution: "Up to 4K at 120fps",
      Audio: "Tempest 3D audio"
    },
    bestSeller: true
  },
  {
    id: "ps5-slim",
    slug: "ps5-slim",
    name: "PlayStation 5 Slim",
    category: "Gaming",
    series: "PlayStation 5",
    price: 549,
    rating: 4.8,
    reviewCount: 156,
    images: getProductImages("ps5-slim"),
    colors: ["White", "Black"],
    storage: ["Disc Edition", "Digital Edition"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month manufacturer warranty",
    deliveryEstimate: "1-2 business days delivery",
    badge: "New",
    description: "A sleeker, quieter, and more efficient version of the PlayStation 5.",
    specs: {
      Design: "30% smaller, 18% lighter",
      Performance: "Identical to standard PS5",
      Storage: "825GB SSD",
      Noise: "Reduced fan noise",
      Thermals: "Improved heat management"
    },
    newArrival: true
  },
  {
    id: "ps5-pro",
    slug: "ps5-pro",
    name: "PlayStation 5 Pro",
    category: "Gaming",
    series: "PlayStation 5",
    price: 799,
    rating: 4.9,
    reviewCount: 89,
    images: getProductImages("ps5-pro"),
    colors: ["White"],
    storage: ["2TB SSD"],
    condition: ["New"],
    availability: "Low Stock",
    warranty: "12-month manufacturer warranty",
    deliveryEstimate: "3-5 business days delivery",
    badge: "Premium",
    description: "Enhanced PS5 with improved GPU, upgraded CPU, and advanced upscaling for ultra-performance gaming.",
    specs: {
      GPU: "67% faster GPU performance",
      Storage: "2TB SSD",
      Performance: "Up to 4K 120fps",
      Upscaling: "AI-powered PS5 Pro Upscaling",
      Audio: "Enhanced Tempest 3D audio"
    }
  },

  // Gaming - Xbox
  {
    id: "xbox-series-x",
    slug: "xbox-series-x",
    name: "Xbox Series X",
    category: "Gaming",
    series: "Xbox Series",
    price: 599,
    rating: 4.8,
    reviewCount: 178,
    images: getProductImages("xbox-series-x"),
    colors: ["Black"],
    storage: ["1TB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month manufacturer warranty",
    deliveryEstimate: "1-2 business days delivery",
    description: "The most powerful gaming console ever built with 12 teraflops of GPU performance.",
    specs: {
      Processor: "Custom AMD Zen 2",
      GPU: "12 TFLOPS RDNA GPU",
      Memory: "16GB GDDR6",
      Storage: "1TB custom SSD",
      Resolution: "Up to 4K at 120fps",
      Backward: "Compatible with thousands of games"
    },
    bestSeller: true
  },
  {
    id: "xbox-series-s",
    slug: "xbox-series-s",
    name: "Xbox Series S",
    category: "Gaming",
    series: "Xbox Series",
    price: 349,
    rating: 4.7,
    reviewCount: 134,
    images: getProductImages("xbox-series-s"),
    colors: ["White"],
    storage: ["512GB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month manufacturer warranty",
    deliveryEstimate: "1-2 business days delivery",
    badge: "Value Pick",
    description: "Next-gen gaming at a great price with 1440p gaming and access to Xbox Game Pass.",
    specs: {
      Processor: "Custom AMD Zen 2",
      GPU: "4 TFLOPS RDNA GPU",
      Memory: "10GB GDDR6",
      Storage: "512GB custom SSD",
      Resolution: "Up to 1440p at 120fps",
      Gaming: "Xbox Game Pass compatible"
    }
  },

  // Gaming - Nintendo
  {
    id: "nintendo-switch",
    slug: "nintendo-switch",
    name: "Nintendo Switch",
    category: "Gaming",
    series: "Nintendo Switch",
    price: 349,
    rating: 4.7,
    reviewCount: 201,
    images: getProductImages("nintendo-switch"),
    colors: ["Gray", "Red/Blue", "White"],
    storage: ["32GB"],
    condition: ["New", "Used"],
    availability: "In Stock",
    warranty: "12-month manufacturer warranty",
    deliveryEstimate: "1-2 business days delivery",
    description: "The revolutionary hybrid console that transforms from handheld to home gaming in seconds.",
    specs: {
      Display: "6.2-inch touchscreen",
      Performance: "Portable and docking capable",
      Storage: "32GB internal (expandable)",
      Battery: "Up to 9 hours",
      Games: "Thousands of titles available"
    },
    bestSeller: true
  },
  {
    id: "nintendo-switch-oled",
    slug: "nintendo-switch-oled",
    name: "Nintendo Switch OLED",
    category: "Gaming",
    series: "Nintendo Switch",
    price: 449,
    rating: 4.9,
    reviewCount: 167,
    images: getProductImages("nintendo-switch-oled"),
    colors: ["White", "Black", "Red/Blue"],
    storage: ["64GB"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month manufacturer warranty",
    deliveryEstimate: "1-2 business days delivery",
    badge: "Premium",
    description: "Enhanced Switch experience with stunning OLED display, improved speakers, and better battery life.",
    specs: {
      Display: "7-inch OLED screen",
      Storage: "64GB internal",
      Battery: "Up to 13 hours",
      Audio: "Enhanced speakers",
      Design: "More refined form factor"
    }
  },

  // Gaming Controllers
  {
    id: "ps5-controller",
    slug: "ps5-controller",
    name: "PlayStation 5 DualSense Controller",
    category: "Controllers",
    series: "PlayStation Accessories",
    price: 89,
    rating: 4.8,
    reviewCount: 93,
    images: getProductImages("ps5-controller"),
    colors: ["White", "Midnight Black", "Starlight Blue", "Galactic Purple"],
    storage: [],
    condition: ["New"],
    availability: "In Stock",
    warranty: "6-month accessory warranty",
    deliveryEstimate: "Same-day pickup available",
    description: "Next-generation gaming controller with haptic feedback and adaptive triggers.",
    specs: {
      Features: "Haptic feedback, adaptive triggers",
      Connectivity: "USB-C rechargeable",
      Battery: "Up to 12 hours",
      Design: "Ergonomic with improved grip",
      Technology: "DualSense innovation"
    }
  },
  {
    id: "xbox-controller",
    slug: "xbox-controller",
    name: "Xbox Series X|S Controller",
    category: "Controllers",
    series: "Xbox Accessories",
    price: 79,
    rating: 4.7,
    reviewCount: 78,
    images: getProductImages("xbox-controller"),
    colors: ["White", "Black", "Blue", "Red"],
    storage: [],
    condition: ["New"],
    availability: "In Stock",
    warranty: "6-month accessory warranty",
    deliveryEstimate: "Same-day pickup available",
    description: "Refined and comfortable controller with textured grips and responsive buttons.",
    specs: {
      Design: "Improved ergonomics",
      Battery: "AA batteries (up to 40 hours)",
      Connectivity: "Wireless 2.4GHz",
      Share: "Built-in share button",
      Compatibility: "Xbox and PC"
    }
  },

  // Gaming Headsets
  {
    id: "gaming-headset-pro",
    slug: "gaming-headset-pro",
    name: "Premium Gaming Headset",
    category: "Gaming Headsets",
    series: "Gaming Accessories",
    price: 199,
    rating: 4.8,
    reviewCount: 112,
    images: getProductImages("gaming-headset"),
    colors: ["Black", "White"],
    storage: ["Wired", "Wireless"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days delivery",
    description: "Professional-grade gaming headset with surround sound, noise cancellation, and dual compatibility.",
    specs: {
      Audio: "7.1 surround sound",
      Microphone: "Noise-cancelling mic",
      Connectivity: "Wireless and wired",
      Comfort: "Memory foam ear cups",
      Compatibility: "Multi-platform"
    }
  }
];

export const getProductBySlug = (slug: string) => products.find((product) => product.slug === slug);

export const getProductsByCategory = (category: ProductCategory) =>
  products.filter((product) => product.category === category);

export const featuredGroups = {
  iphones: products.filter((product) => product.category === "iPhone").slice(0, 3),
  macbooks: products.filter((product) => product.category === "MacBook"),
  ipads: products.filter((product) => product.category === "iPad"),
  watches: products.filter((product) => product.category === "Apple Watch"),
  airpods: products.filter((product) => product.category === "AirPods"),
  accessories: products.filter((product) =>
    ["Accessories", "Cases", "Chargers", "Power Banks", "Adapters", "Cables"].includes(product.category)
  ),
  gaming: products.filter((product) =>
    ["Gaming", "PlayStation", "Xbox", "Nintendo", "Controllers", "Gaming Headsets"].includes(product.category)
  ).slice(0, 6),
  bestSellers: products.filter((product) => product.bestSeller),
  newArrivals: products.filter((product) => product.newArrival),
  deals: products.filter((product) => product.deal)
};
