import type { Product, ProductCategory } from "@/types";
import { getProductImages } from "@/lib/images";

export const categories: ProductCategory[] = [
  "iPhone",
  "MacBook",
  "iPad",
  "Apple Watch",
  "AirPods",
  "Apple TV",
  "HomePod",
  "Accessories",
  "Cases",
  "Chargers",
  "Power Banks",
  "Screen Protectors",
  "Adapters",
  "Cables",
  "Speakers",
  "Smart Accessories",
  "Gaming",
  "PlayStation",
  "Xbox",
  "Nintendo",
  "Controllers",
  "Gaming Headsets"
];

export const products: Product[] = [
  // ===================================
  // IPHONE CATALOG
  // ===================================
  {
    id: "iphone-16-pro-max",
    slug: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    category: "iPhone",
    series: "iPhone 16 Series",
    price: 1299,
    compareAtPrice: 1399,
    rating: 4.9,
    reviewCount: 248,
    images: getProductImages("iphone-16-pro-max", "iPhone"),
    colors: ["Natural Titanium", "Desert Titanium", "Black Titanium", "White Titanium"],
    storage: ["256GB", "512GB", "1TB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month TroyX Ghana warranty",
    deliveryEstimate: "Same-day pickup or 1-2 business days delivery",
    badge: "Best Seller",
    description: "The ultimate iPhone with a 6.9-inch Super Retina XDR display, A18 Pro chip, 48MP Fusion camera system, and Camera Control.",
    specs: { Display: "6.9-inch OLED", Chip: "A18 Pro", Camera: "48MP Pro System", Charging: "USB-C" },
    bestSeller: true,
    newArrival: true,
    deal: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "iphone-16-pro",
    slug: "iphone-16-pro",
    name: "iPhone 16 Pro",
    category: "iPhone",
    series: "iPhone 16 Series",
    price: 999,
    compareAtPrice: 1099,
    rating: 4.9,
    reviewCount: 182,
    images: getProductImages("iphone-16-pro", "iPhone"),
    colors: ["Natural Titanium", "Desert Titanium", "Black Titanium"],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "Same-day pickup or 1-2 business days",
    badge: "Flagship Pro",
    description: "6.3-inch Super Retina XDR display, A18 Pro chip, 5x Telephoto optical zoom camera system.",
    specs: { Display: "6.3-inch OLED", Chip: "A18 Pro", Camera: "48MP Triple Lens", Charging: "USB-C" },
    bestSeller: true,
    newArrival: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "iphone-16-plus",
    slug: "iphone-16-plus",
    name: "iPhone 16 Plus",
    category: "iPhone",
    series: "iPhone 16 Series",
    price: 899,
    compareAtPrice: 949,
    rating: 4.8,
    reviewCount: 94,
    images: getProductImages("iphone-16-plus", "iPhone"),
    colors: ["Teal", "Pink", "Ultramarine", "Black", "White"],
    storage: ["128GB", "256GB", "512GB"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "Same-day pickup or 1-3 business days",
    badge: "Big Screen Value",
    description: "6.7-inch Super Retina XDR display with A18 chip, Camera Control, and extraordinary battery life.",
    specs: { Display: "6.7-inch OLED", Chip: "A18", Camera: "48MP Dual Lens", Charging: "USB-C" },
    newArrival: true,
    vendorId: "v-itech-ghana",
    vendorName: "iTech Ghana Store",
    vendorSlug: "itech-ghana",
    isVerifiedVendor: true
  },
  {
    id: "iphone-16",
    slug: "iphone-16",
    name: "iPhone 16",
    category: "iPhone",
    series: "iPhone 16 Series",
    price: 799,
    compareAtPrice: 849,
    rating: 4.8,
    reviewCount: 142,
    images: getProductImages("iphone-16", "iPhone"),
    colors: ["Teal", "Pink", "Ultramarine", "Black"],
    storage: ["128GB", "256GB", "512GB"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "Same-day pickup or 1-2 business days",
    badge: "Popular Choice",
    description: "6.1-inch Super Retina XDR display with Action Button, Camera Control, and A18 performance.",
    specs: { Display: "6.1-inch OLED", Chip: "A18", Camera: "48MP Fusion", Charging: "USB-C" },
    bestSeller: true,
    newArrival: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "iphone-15-pro-max",
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "iPhone",
    series: "iPhone 15 Series",
    price: 1099,
    compareAtPrice: 1199,
    rating: 4.9,
    reviewCount: 310,
    images: getProductImages("iphone-15-pro-max", "iPhone"),
    colors: ["Natural Titanium", "Blue Titanium", "Black Titanium"],
    storage: ["256GB", "512GB", "1TB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Special Deal",
    description: "Titanium design with A17 Pro chip, Action button, 5x Optical Telephoto zoom, and USB-C speed.",
    specs: { Display: "6.7-inch OLED", Chip: "A17 Pro", Camera: "48MP Triple System", Charging: "USB-C" },
    deal: true,
    vendorId: "v-accra-premium",
    vendorName: "Accra Premium Electronics",
    vendorSlug: "accra-premium-electronics",
    isVerifiedVendor: true
  },
  {
    id: "iphone-15-pro",
    slug: "iphone-15-pro",
    name: "iPhone 15 Pro",
    category: "iPhone",
    series: "iPhone 15 Series",
    price: 899,
    compareAtPrice: 999,
    rating: 4.8,
    reviewCount: 215,
    images: getProductImages("iphone-15-pro", "iPhone"),
    colors: ["Natural Titanium", "Blue Titanium", "White Titanium"],
    storage: ["128GB", "256GB", "512GB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Best Value Pro",
    description: "A17 Pro performance with Pro camera capabilities in a lightweight titanium body.",
    specs: { Display: "6.1-inch OLED", Chip: "A17 Pro", Camera: "48MP Triple System", Charging: "USB-C" },
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "iphone-15-plus",
    slug: "iphone-15-plus",
    name: "iPhone 15 Plus",
    category: "iPhone",
    series: "iPhone 15 Series",
    price: 749,
    compareAtPrice: 849,
    rating: 4.7,
    reviewCount: 88,
    images: getProductImages("iphone-15-plus", "iPhone"),
    colors: ["Pink", "Yellow", "Green", "Blue", "Black"],
    storage: ["128GB", "256GB"],
    condition: ["New", "Used"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Dynamic Island with 48MP Main camera, 6.7-inch display, and all-day battery performance.",
    specs: { Display: "6.7-inch OLED", Chip: "A16 Bionic", Camera: "48MP Dual Lens", Charging: "USB-C" },
    vendorId: "v-mobilezone-kumasi",
    vendorName: "MobileZone Kumasi",
    vendorSlug: "mobilezone-kumasi",
    isVerifiedVendor: true
  },
  {
    id: "iphone-15",
    slug: "iphone-15",
    name: "iPhone 15",
    category: "iPhone",
    series: "iPhone 15 Series",
    price: 699,
    compareAtPrice: 799,
    rating: 4.8,
    reviewCount: 304,
    images: getProductImages("iphone-15", "iPhone"),
    colors: ["Pink", "Yellow", "Green", "Blue", "Black"],
    storage: ["128GB", "256GB", "512GB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Popular Value",
    description: "Dynamic Island, 48MP camera, color-infused glass, and durable aluminum design.",
    specs: { Display: "6.1-inch OLED", Chip: "A16 Bionic", Camera: "48MP Dual Lens", Charging: "USB-C" },
    deal: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "iphone-14-plus",
    slug: "iphone-14-plus",
    name: "iPhone 14 Plus",
    category: "iPhone",
    series: "iPhone 14 Series",
    price: 629,
    compareAtPrice: 699,
    rating: 4.7,
    reviewCount: 76,
    images: getProductImages("iphone-14-plus", "iPhone"),
    colors: ["Midnight", "Starlight", "Purple", "Blue"],
    storage: ["128GB", "256GB"],
    condition: ["Used", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Big 6.7-inch display, dual camera system, Crash Detection, and ultra-long battery life.",
    specs: { Display: "6.7-inch OLED", Chip: "A15 Bionic", Camera: "12MP Dual Lens", Charging: "Lightning" },
    vendorId: "v-itech-ghana",
    vendorName: "iTech Ghana Store",
    vendorSlug: "itech-ghana",
    isVerifiedVendor: true
  },
  {
    id: "iphone-14",
    slug: "iphone-14",
    name: "iPhone 14",
    category: "iPhone",
    series: "iPhone 14 Series",
    price: 549,
    compareAtPrice: 629,
    rating: 4.7,
    reviewCount: 260,
    images: getProductImages("iphone-14", "iPhone"),
    colors: ["Midnight", "Starlight", "Purple", "PRODUCT(RED)"],
    storage: ["128GB", "256GB"],
    condition: ["Used", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "6.1-inch Super Retina XDR display, dual-camera system, Action Mode video stabilization.",
    specs: { Display: "6.1-inch OLED", Chip: "A15 Bionic", Camera: "12MP Dual Lens", Charging: "Lightning" },
    vendorId: "v-accra-premium",
    vendorName: "Accra Premium Electronics",
    vendorSlug: "accra-premium-electronics",
    isVerifiedVendor: true
  },
  {
    id: "iphone-13",
    slug: "iphone-13",
    name: "iPhone 13",
    category: "iPhone",
    series: "iPhone 13 Series",
    price: 479,
    compareAtPrice: 549,
    rating: 4.8,
    reviewCount: 410,
    images: getProductImages("iphone-13", "iPhone"),
    colors: ["Midnight", "Starlight", "Blue", "Pink"],
    storage: ["128GB", "256GB"],
    condition: ["Used", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Budget iPhone",
    description: "Cinematic mode video recording, durable flat-edge design, and bright Super Retina XDR display.",
    specs: { Display: "6.1-inch OLED", Chip: "A15 Bionic", Camera: "12MP Dual Lens", Charging: "Lightning" },
    deal: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "iphone-se",
    slug: "iphone-se",
    name: "iPhone SE (3rd Gen)",
    category: "iPhone",
    series: "iPhone SE Series",
    price: 379,
    compareAtPrice: 429,
    rating: 4.6,
    reviewCount: 115,
    images: getProductImages("iphone-se", "iPhone"),
    colors: ["Midnight", "Starlight", "Red"],
    storage: ["64GB", "128GB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Compact 4.7-inch Retina HD display, Touch ID Home button, A15 Bionic performance.",
    specs: { Display: "4.7-inch LCD", Chip: "A15 Bionic", Camera: "12MP Single Lens", Charging: "Lightning" },
    vendorId: "v-mobilezone-kumasi",
    vendorName: "MobileZone Kumasi",
    vendorSlug: "mobilezone-kumasi",
    isVerifiedVendor: true
  },

  // ===================================
  // MAC / MACBOOK CATALOG
  // ===================================
  {
    id: "macbook-air-13",
    slug: "macbook-air-13",
    name: 'MacBook Air 13" M3',
    category: "MacBook",
    series: "MacBook Air",
    price: 1099,
    compareAtPrice: 1199,
    rating: 4.9,
    reviewCount: 165,
    images: getProductImages("macbook-air-13", "MacBook"),
    colors: ["Midnight", "Starlight", "Space Gray", "Silver"],
    storage: ["256GB SSD", "512GB SSD", "1TB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "Same-day pickup or 1-2 business days",
    badge: "Top Seller Laptop",
    description: "Lean, mean M3 machine. Ultra-thin fanless design, up to 18 hours battery life, Liquid Retina display.",
    specs: { Display: '13.6-inch Liquid Retina', Chip: "Apple M3 8-core CPU", Memory: "8GB/16GB Unified", Charging: "MagSafe 3" },
    bestSeller: true,
    newArrival: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "macbook-air-15",
    slug: "macbook-air-15",
    name: 'MacBook Air 15" M3',
    category: "MacBook",
    series: "MacBook Air",
    price: 1299,
    compareAtPrice: 1399,
    rating: 4.9,
    reviewCount: 98,
    images: getProductImages("macbook-air-15", "MacBook"),
    colors: ["Midnight", "Starlight", "Space Gray"],
    storage: ["256GB SSD", "512GB SSD", "1TB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "1-2 business days",
    description: "Immersive 15.3-inch display with powerful M3 performance and six-speaker sound system.",
    specs: { Display: '15.3-inch Liquid Retina', Chip: "Apple M3 8-core CPU", Memory: "16GB Unified", Charging: "MagSafe 3" },
    newArrival: true,
    vendorId: "v-itech-ghana",
    vendorName: "iTech Ghana Store",
    vendorSlug: "itech-ghana",
    isVerifiedVendor: true
  },
  {
    id: "macbook-pro-14",
    slug: "macbook-pro-14",
    name: 'MacBook Pro 14" M3 Pro',
    category: "MacBook",
    series: "MacBook Pro",
    price: 1999,
    compareAtPrice: 2199,
    rating: 4.9,
    reviewCount: 140,
    images: getProductImages("macbook-pro-14", "MacBook"),
    colors: ["Space Black", "Silver"],
    storage: ["512GB SSD", "1TB SSD", "2TB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "Same-day pickup or 1-2 business days",
    badge: "Pro Workstation",
    description: "M3 Pro chip with Liquid Retina XDR display, HDMI port, SDXC card slot, and Space Black finish.",
    specs: { Display: '14.2-inch XDR 120Hz', Chip: "Apple M3 Pro 11-core CPU", Memory: "18GB Unified", Charging: "MagSafe 3" },
    bestSeller: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "macbook-pro-16",
    slug: "macbook-pro-16",
    name: 'MacBook Pro 16" M3 Max',
    category: "MacBook",
    series: "MacBook Pro",
    price: 3499,
    compareAtPrice: 3799,
    rating: 5.0,
    reviewCount: 82,
    images: getProductImages("macbook-pro-16", "MacBook"),
    colors: ["Space Black", "Silver"],
    storage: ["1TB SSD", "2TB SSD", "4TB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Extreme Power",
    description: "The ultimate laptop for developers, 3D artists, and 8K video editors with M3 Max horsepower.",
    specs: { Display: '16.2-inch XDR 120Hz', Chip: "Apple M3 Max 16-core CPU", Memory: "36GB Unified", Charging: "MagSafe 3" },
    vendorId: "v-accra-premium",
    vendorName: "Accra Premium Electronics",
    vendorSlug: "accra-premium-electronics",
    isVerifiedVendor: true
  },
  {
    id: "imac-24",
    slug: "imac-24",
    name: 'iMac 24" M3 All-In-One',
    category: "MacBook",
    series: "iMac",
    price: 1299,
    compareAtPrice: 1399,
    rating: 4.8,
    reviewCount: 46,
    images: getProductImages("imac-24", "MacBook"),
    colors: ["Blue", "Green", "Pink", "Silver"],
    storage: ["256GB SSD", "512GB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Striking 24-inch 4.5K Retina display, 1080p FaceTime camera, and color-matched Magic Keyboard.",
    specs: { Display: "24-inch 4.5K Retina", Chip: "Apple M3 8-core CPU", Memory: "8GB Unified", Ports: "Thunderbolt 4" },
    vendorId: "v-itech-ghana",
    vendorName: "iTech Ghana Store",
    vendorSlug: "itech-ghana",
    isVerifiedVendor: true
  },
  {
    id: "mac-mini",
    slug: "mac-mini",
    name: "Mac Mini M2 Pro",
    category: "MacBook",
    series: "Mac Desktop",
    price: 599,
    compareAtPrice: 649,
    rating: 4.8,
    reviewCount: 92,
    images: getProductImages("mac-mini", "MacBook"),
    colors: ["Silver"],
    storage: ["256GB SSD", "512GB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Compact Workstation",
    description: "Compact desktop powerhouse with M2 speed, versatile ports, and low power consumption.",
    specs: { Display: "External Monitor Support", Chip: "Apple M2 8-core CPU", Memory: "8GB/16GB Unified" },
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "mac-studio",
    slug: "mac-studio",
    name: "Mac Studio M2 Max",
    category: "MacBook",
    series: "Mac Desktop",
    price: 1999,
    compareAtPrice: 2199,
    rating: 4.9,
    reviewCount: 38,
    images: getProductImages("mac-studio", "MacBook"),
    colors: ["Silver"],
    storage: ["512GB SSD", "1TB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Outrageous performance and extensive connectivity in an incredibly compact footprint.",
    specs: { Display: "Up to 8 Displays", Chip: "Apple M2 Max 12-core", Memory: "32GB Unified" },
    vendorId: "v-accra-premium",
    vendorName: "Accra Premium Electronics",
    vendorSlug: "accra-premium-electronics",
    isVerifiedVendor: true
  },
  {
    id: "studio-display",
    slug: "studio-display",
    name: 'Apple Studio Display 27"',
    category: "MacBook",
    series: "Displays",
    price: 1599,
    compareAtPrice: 1699,
    rating: 4.8,
    reviewCount: 54,
    images: getProductImages("studio-display", "MacBook"),
    colors: ["Silver"],
    storage: ["Standard Glass", "Nano-Texture Glass"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Immersive 27-inch 5K Retina display with 12MP Ultra Wide camera, studio-quality mics, and 6-speaker audio.",
    specs: { Display: "27-inch 5K Retina 600 nits", Camera: "12MP Ultra Wide Center Stage", Audio: "Spatial Audio 6-Speakers" },
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },

  // ===================================
  // IPAD CATALOG
  // ===================================
  {
    id: "ipad-pro-13-m4",
    slug: "ipad-pro-13-m4",
    name: 'iPad Pro 13" M4',
    category: "iPad",
    series: "iPad Pro",
    price: 1299,
    compareAtPrice: 1399,
    rating: 5.0,
    reviewCount: 78,
    images: getProductImages("ipad-pro-13-m4", "iPad"),
    colors: ["Space Black", "Silver"],
    storage: ["256GB", "512GB", "1TB", "2TB"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "Same-day pickup or 1-2 business days",
    badge: "Ultra Thin M4",
    description: "Breakthrough Ultra Retina XDR Tandem OLED display, ridiculously thin design, powered by M4 chip.",
    specs: { Display: '13-inch Tandem OLED', Chip: "Apple M4", Camera: "12MP Wide 4K Video", Accessories: "Apple Pencil Pro" },
    bestSeller: true,
    newArrival: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "ipad-pro-11-m4",
    slug: "ipad-pro-11-m4",
    name: 'iPad Pro 11" M4',
    category: "iPad",
    series: "iPad Pro",
    price: 999,
    compareAtPrice: 1099,
    rating: 4.9,
    reviewCount: 65,
    images: getProductImages("ipad-pro-11-m4", "iPad"),
    colors: ["Space Black", "Silver"],
    storage: ["256GB", "512GB", "1TB"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Portable 11-inch Ultra Retina XDR Tandem OLED display with extreme M4 graphics.",
    specs: { Display: '11-inch Tandem OLED', Chip: "Apple M4", Camera: "12MP Wide", Charging: "USB-C Thunderbolt" },
    newArrival: true,
    vendorId: "v-itech-ghana",
    vendorName: "iTech Ghana Store",
    vendorSlug: "itech-ghana",
    isVerifiedVendor: true
  },
  {
    id: "ipad-air-11",
    slug: "ipad-air-11",
    name: 'iPad Air 11" M2',
    category: "iPad",
    series: "iPad Air",
    price: 599,
    compareAtPrice: 649,
    rating: 4.8,
    reviewCount: 112,
    images: getProductImages("ipad-air-11", "iPad"),
    colors: ["Space Gray", "Starlight", "Purple", "Blue"],
    storage: ["128GB", "256GB", "512GB"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Versatile Choice",
    description: "Fresh M2 performance, Liquid Retina display, Touch ID, and Apple Pencil Pro support.",
    specs: { Display: "11-inch Liquid Retina", Chip: "Apple M2", Camera: "12MP Center Stage" },
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "ipad-11th-gen",
    slug: "ipad-11th-gen",
    name: "iPad 10th Gen (10.9-inch)",
    category: "iPad",
    series: "Standard iPad",
    price: 349,
    compareAtPrice: 399,
    rating: 4.7,
    reviewCount: 190,
    images: getProductImages("ipad-11th-gen", "iPad"),
    colors: ["Blue", "Pink", "Yellow", "Silver"],
    storage: ["64GB", "256GB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Best Value iPad",
    description: "All-screen design with 10.9-inch Liquid Retina display, A14 Bionic chip, landscape front camera.",
    specs: { Display: "10.9-inch Liquid Retina", Chip: "A14 Bionic", Camera: "12MP Landscape" },
    deal: true,
    vendorId: "v-mobilezone-kumasi",
    vendorName: "MobileZone Kumasi",
    vendorSlug: "mobilezone-kumasi",
    isVerifiedVendor: true
  },
  {
    id: "ipad-mini",
    slug: "ipad-mini",
    name: "iPad Mini 7 (A17 Pro)",
    category: "iPad",
    series: "iPad Mini",
    price: 499,
    compareAtPrice: 549,
    rating: 4.8,
    reviewCount: 52,
    images: getProductImages("ipad-mini", "iPad"),
    colors: ["Space Gray", "Starlight", "Purple", "Blue"],
    storage: ["128GB", "256GB", "512GB"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Mega power in mini size. 8.3-inch Liquid Retina display powered by A17 Pro chip and Apple Intelligence.",
    specs: { Display: "8.3-inch Liquid Retina", Chip: "A17 Pro", Stylus: "Apple Pencil Pro Support" },
    newArrival: true,
    vendorId: "v-accra-premium",
    vendorName: "Accra Premium Electronics",
    vendorSlug: "accra-premium-electronics",
    isVerifiedVendor: true
  },

  // ===================================
  // APPLE WATCH CATALOG
  // ===================================
  {
    id: "apple-watch-ultra-2",
    slug: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2",
    category: "Apple Watch",
    series: "Ultra Series",
    price: 799,
    compareAtPrice: 849,
    rating: 4.9,
    reviewCount: 135,
    images: getProductImages("apple-watch-ultra-2", "Apple Watch"),
    colors: ["Black Titanium", "Natural Titanium"],
    storage: ["64GB"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX warranty",
    deliveryEstimate: "Same-day pickup or 1-2 business days",
    badge: "Rugged Outdoor",
    description: "The most capable Apple Watch with 3000 nits display, S9 SiP Double Tap gesture, precision GPS.",
    specs: { Case: "49mm Titanium", Display: "3000 nits Sapphire", Battery: "Up to 72 hrs Low Power" },
    bestSeller: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "apple-watch-series-10",
    slug: "apple-watch-series-10",
    name: "Apple Watch Series 10",
    category: "Apple Watch",
    series: "Series 10",
    price: 399,
    compareAtPrice: 429,
    rating: 4.8,
    reviewCount: 96,
    images: getProductImages("apple-watch-series-10", "Apple Watch"),
    colors: ["Jet Black", "Rose Gold", "Silver", "Slate Titanium"],
    storage: ["64GB"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Thinnest Design",
    description: "Thinnest Apple Watch ever with largest display area, wide-angle OLED display, and depth gauge.",
    specs: { Case: "42mm / 46mm Aluminum or Titanium", Display: "Wide-Angle OLED", Charging: "Fast Charge 80% in 30min" },
    newArrival: true,
    vendorId: "v-itech-ghana",
    vendorName: "iTech Ghana Store",
    vendorSlug: "itech-ghana",
    isVerifiedVendor: true
  },
  {
    id: "apple-watch-se",
    slug: "apple-watch-se",
    name: "Apple Watch SE (2nd Gen)",
    category: "Apple Watch",
    series: "SE Series",
    price: 249,
    compareAtPrice: 279,
    rating: 4.7,
    reviewCount: 210,
    images: getProductImages("apple-watch-se", "Apple Watch"),
    colors: ["Midnight", "Starlight", "Silver"],
    storage: ["32GB"],
    condition: ["New", "Refurbished"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Essential fitness tracking, Heart Rate notifications, Crash Detection, and water resistance to 50m.",
    specs: { Case: "40mm / 44mm Aluminum", Sensors: "Optical Heart Rate", Water: "50m Water Resistant" },
    deal: true,
    vendorId: "v-mobilezone-kumasi",
    vendorName: "MobileZone Kumasi",
    vendorSlug: "mobilezone-kumasi",
    isVerifiedVendor: true
  },

  // ===================================
  // AIRPODS & AUDIO CATALOG
  // ===================================
  {
    id: "airpods-pro-2",
    slug: "airpods-pro-2",
    name: "AirPods Pro 2 (USB-C)",
    category: "AirPods",
    series: "Pro Audio",
    price: 249,
    compareAtPrice: 279,
    rating: 4.9,
    reviewCount: 380,
    images: getProductImages("airpods-pro-2", "AirPods"),
    colors: ["White"],
    storage: ["USB-C MagSafe Case"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "Same-day pickup or 1-2 business days",
    badge: "Best Noise Cancelling",
    description: "Up to 2x more Active Noise Cancellation, Adaptive Audio, Conversation Awareness, and USB-C MagSafe case.",
    specs: { ANC: "2x Active Noise Cancellation", Chip: "H2 Headphone Chip", Battery: "Up to 30 hrs with Case" },
    bestSeller: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "airpods-4-anc",
    slug: "airpods-4-anc",
    name: "AirPods 4 with Active Noise Cancellation",
    category: "AirPods",
    series: "AirPods 4",
    price: 179,
    compareAtPrice: 199,
    rating: 4.8,
    reviewCount: 84,
    images: getProductImages("airpods-4-anc", "AirPods"),
    colors: ["White"],
    storage: ["Wireless USB-C Case"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Open-Ear ANC",
    description: "First open-ear design with Active Noise Cancellation, Transparency mode, and H2 chip clarity.",
    specs: { ANC: "Open-Ear Active Noise Cancellation", Chip: "H2 Chip", Charging: "USB-C + Qi Wireless" },
    newArrival: true,
    vendorId: "v-itech-ghana",
    vendorName: "iTech Ghana Store",
    vendorSlug: "itech-ghana",
    isVerifiedVendor: true
  },
  {
    id: "airpods-4",
    slug: "airpods-4",
    name: "AirPods 4",
    category: "AirPods",
    series: "AirPods 4",
    price: 129,
    compareAtPrice: 149,
    rating: 4.7,
    reviewCount: 105,
    images: getProductImages("airpods-4", "AirPods"),
    colors: ["White"],
    storage: ["USB-C Case"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Re-engineered acoustic architecture with Personalized Spatial Audio and head tracking.",
    specs: { Audio: "Personalized Spatial Audio", Chip: "H2 Chip", Case: "USB-C Compact Case" },
    vendorId: "v-accra-premium",
    vendorName: "Accra Premium Electronics",
    vendorSlug: "accra-premium-electronics",
    isVerifiedVendor: true
  },
  {
    id: "airpods-max",
    slug: "airpods-max",
    name: "AirPods Max (USB-C)",
    category: "AirPods",
    series: "Max Headband",
    price: 549,
    compareAtPrice: 599,
    rating: 4.8,
    reviewCount: 142,
    images: getProductImages("airpods-max", "AirPods"),
    colors: ["Midnight", "Starlight", "Blue", "Purple", "Orange"],
    storage: ["USB-C Smart Case"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Over-Ear Luxury",
    description: "High-fidelity audio masterwork with custom dynamic driver, Pro Active Noise Cancellation, and USB-C.",
    specs: { Audio: "High-Fidelity Dynamic Driver", ANC: "Pro Active Noise Cancellation", Charging: "USB-C" },
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },

  // ===================================
  // ACCESSORIES & CHARGERS
  // ===================================
  {
    id: "apple-pencil-pro",
    slug: "apple-pencil-pro",
    name: "Apple Pencil Pro",
    category: "Accessories",
    series: "Pencil",
    price: 129,
    compareAtPrice: 139,
    rating: 4.9,
    reviewCount: 75,
    images: getProductImages("apple-pencil-pro", "Accessories"),
    colors: ["White"],
    storage: ["Magnetic Wireless"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Squeeze & Barrel Roll",
    description: "Haptic feedback engine, squeeze gesture toolbar, barrel roll rotation sensor, and Find My location.",
    specs: { Compatibility: "iPad Pro M4 / iPad Air M2", Precision: "Pixel-perfect low latency" },
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "magic-keyboard",
    slug: "magic-keyboard",
    name: "Magic Keyboard for iPad Pro 13-inch",
    category: "Accessories",
    series: "Keyboards",
    price: 349,
    compareAtPrice: 379,
    rating: 4.8,
    reviewCount: 48,
    images: getProductImages("magic-keyboard", "Accessories"),
    colors: ["Space Black", "White"],
    storage: ["Aluminum Palm Rest"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Cantilever floating design, glass haptic trackpad, function row keys, and aluminum wrist rest.",
    specs: { Trackpad: "Haptic Glass", Construction: "Machined Aluminum" },
    vendorId: "v-itech-ghana",
    vendorName: "iTech Ghana Store",
    vendorSlug: "itech-ghana",
    isVerifiedVendor: true
  },
  {
    id: "magsafe-charger",
    slug: "magsafe-charger",
    name: "Apple MagSafe Charger (25W)",
    category: "Chargers",
    series: "MagSafe",
    price: 39,
    compareAtPrice: 49,
    rating: 4.7,
    reviewCount: 280,
    images: getProductImages("magsafe-charger", "Chargers"),
    colors: ["Silver/White"],
    storage: ["1m Cable", "2m Cable"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "Fast wireless charging up to 25W for iPhone 16 series with perfectly aligned magnetic snap.",
    specs: { Speed: "Up to 25W Fast Charging", Connector: "USB-C" },
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "airtag-4pack",
    slug: "airtag-4pack",
    name: "Apple AirTag (4-Pack)",
    category: "Accessories",
    series: "Find My",
    price: 99,
    compareAtPrice: 119,
    rating: 4.9,
    reviewCount: 310,
    images: getProductImages("airtag-4pack", "Accessories"),
    colors: ["White/Stainless Steel"],
    storage: ["4 Tags included"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Must-Have Accessory",
    description: "Keep track of keys, bags, luggage, and electronics in the Find My app with Precision Finding.",
    specs: { Battery: "User Replaceable CR2032", Water: "IP67 Water-Resistant" },
    bestSeller: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },

  // ===================================
  // GAMING CONSOLES & ACCESSORIES
  // ===================================
  {
    id: "ps5-pro",
    slug: "ps5-pro",
    name: "PlayStation 5 Pro Console",
    category: "Gaming",
    series: "PlayStation",
    price: 699,
    compareAtPrice: 749,
    rating: 4.9,
    reviewCount: 156,
    images: getProductImages("ps5-pro", "Gaming"),
    colors: ["White/Black"],
    storage: ["2TB High-Speed SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month TroyX Gaming warranty",
    deliveryEstimate: "Same-day pickup or 1-2 business days",
    badge: "Flagship 4K 120fps",
    description: "PlayStation Spectral Super Resolution (PSSR) AI upscaling, upgraded GPU, 2TB SSD, and 60fps Ray Tracing.",
    specs: { Storage: "2TB NVMe SSD", Output: "4K 120Hz / 8K VRR", Audio: "3D Tempest Audio" },
    bestSeller: true,
    newArrival: true,
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  },
  {
    id: "ps5-slim",
    slug: "ps5-slim",
    name: "PlayStation 5 Slim Digital / Disc Edition",
    category: "Gaming",
    series: "PlayStation",
    price: 499,
    compareAtPrice: 549,
    rating: 4.8,
    reviewCount: 240,
    images: getProductImages("ps5-slim", "Gaming"),
    colors: ["White"],
    storage: ["1TB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Popular Console",
    description: "Sleeker design with 1TB SSD, DualSense wireless controller, 4K HDR ray-traced visuals.",
    specs: { Storage: "1TB Custom SSD", Controller: "DualSense Haptic" },
    vendorId: "v-itech-ghana",
    vendorName: "iTech Ghana Store",
    vendorSlug: "itech-ghana",
    isVerifiedVendor: true
  },
  {
    id: "xbox-series-x",
    slug: "xbox-series-x",
    name: "Xbox Series X (1TB / 2TB Galaxy Black)",
    category: "Gaming",
    series: "Xbox",
    price: 499,
    compareAtPrice: 549,
    rating: 4.8,
    reviewCount: 110,
    images: getProductImages("xbox-series-x", "Gaming"),
    colors: ["Matte Black", "Galaxy Black Special Edition"],
    storage: ["1TB SSD", "2TB SSD"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    description: "The fastest, most powerful Xbox ever with 12 teraflops GPU horsepower and Quick Resume.",
    specs: { GPU: "12 TFLOPS RDNA 2", Storage: "1TB Custom NVMe" },
    vendorId: "v-accra-premium",
    vendorName: "Accra Premium Electronics",
    vendorSlug: "accra-premium-electronics",
    isVerifiedVendor: true
  },
  {
    id: "nintendo-switch-oled",
    slug: "nintendo-switch-oled",
    name: "Nintendo Switch OLED Model",
    category: "Gaming",
    series: "Nintendo",
    price: 349,
    compareAtPrice: 379,
    rating: 4.8,
    reviewCount: 175,
    images: getProductImages("nintendo-switch-oled", "Gaming"),
    colors: ["White Joy-Con", "Neon Red/Blue", "Mario Red Edition"],
    storage: ["64GB Internal"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Handheld Champion",
    description: "Vibrant 7-inch OLED screen, wide adjustable stand, wired LAN dock port, 64GB storage.",
    specs: { Display: "7-inch OLED Touchscreen", Battery: "Up to 9 hrs Handheld" },
    vendorId: "v-mobilezone-kumasi",
    vendorName: "MobileZone Kumasi",
    vendorSlug: "mobilezone-kumasi",
    isVerifiedVendor: true
  },
  {
    id: "dualsense-edge-controller",
    slug: "dualsense-edge-controller",
    name: "PlayStation DualSense Edge Wireless Controller",
    category: "Controllers",
    series: "PlayStation",
    price: 199,
    compareAtPrice: 219,
    rating: 4.9,
    reviewCount: 64,
    images: getProductImages("dualsense-edge-controller", "Gaming"),
    colors: ["White/Black"],
    storage: ["Carrying Case included"],
    condition: ["New"],
    availability: "In Stock",
    warranty: "12-month warranty",
    deliveryEstimate: "1-2 business days",
    badge: "Pro Esports Controller",
    description: "Customizable controls, remappable rear back buttons, changeable stick caps and module triggers.",
    specs: { Customization: "Remappable Back Buttons", Haptics: "Adaptive Triggers" },
    vendorId: "v-troyx-flagship",
    vendorName: "TroyX iStore Flagship",
    vendorSlug: "troyx-official",
    isVerifiedVendor: true
  }
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return products.filter((product) => product.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.bestSeller || product.newArrival || product.deal);
}

export const featuredGroups = {
  bestSellers: products.filter((p) => p.bestSeller),
  newArrivals: products.filter((p) => p.newArrival),
  deals: products.filter((p) => p.deal),
  gaming: products.filter((p) => ["Gaming", "PlayStation", "Xbox", "Nintendo", "Controllers", "Gaming Headsets"].includes(p.category))
};

